// Static list used by SmartAutocomplete for category / segmento / nicho fields.
// Fuzzy match tolerates accents, case and small typos.

export const CATEGORY_SUGGESTIONS: string[] = [
  "Padaria",
  "Padaria Artesanal",
  "Confeitaria",
  "Cafeteria",
  "Restaurante",
  "Restaurante Italiano",
  "Restaurante Japonês",
  "Pizzaria",
  "Hamburgueria",
  "Açaí",
  "Sorveteria",
  "Lanchonete",
  "Bar",
  "Boteco",
  "Pub",
  "Choperia",
  "Depósito de Bebidas",
  "Distribuidora de Bebidas",
  "Adega",
  "Mercado",
  "Hortifruti",
  "Empório",
  "Açougue",
  "Peixaria",
  "Pet Shop",
  "Pet Grooming",
  "Hospital Veterinário",
  "Clínica Veterinária",
  "Farmácia",
  "Drogaria",
  "Manipulação",
  "Salão de Beleza",
  "Barbearia",
  "Estúdio de Sobrancelhas",
  "Estúdio de Unhas",
  "Depilação",
  "Clínica de Estética",
  "SPA",
  "Massagem",
  "Academia",
  "Crossfit",
  "Pilates",
  "Yoga",
  "Muay Thai",
  "Jiu-Jitsu",
  "Estúdio de Dança",
  "Personal Trainer",
  "Nutricionista",
  "Psicólogo",
  "Consultório Odontológico",
  "Clínica Odontológica",
  "Ortodontista",
  "Clínica Médica",
  "Fisioterapia",
  "Advogado",
  "Escritório de Advocacia",
  "Contador",
  "Escritório de Contabilidade",
  "Arquiteto",
  "Escritório de Arquitetura",
  "Engenheiro",
  "Designer de Interiores",
  "Imobiliária",
  "Corretor de Imóveis",
  "Corretor de Seguros",
  "Escola",
  "Escola de Idiomas",
  "Curso de Inglês",
  "Escola de Música",
  "Autoescola",
  "Faculdade",
  "Berçário",
  "Creche",
  "Marcenaria",
  "Serralheria",
  "Vidraçaria",
  "Reforma e Construção",
  "Loja de Materiais de Construção",
  "Depósito de Construção",
  "Laje e Pré-moldados",
  "Loja de Móveis",
  "Loja de Decoração",
  "Loja de Roupas",
  "Loja de Calçados",
  "Loja de Cosméticos",
  "Ótica",
  "Joalheria",
  "Papelaria",
  "Livraria",
  "Loja de Brinquedos",
  "Loja de Informática",
  "Assistência Técnica",
  "Assistência Técnica de Celulares",
  "Oficina Mecânica",
  "Auto Elétrica",
  "Funilaria e Pintura",
  "Lava-Jato",
  "Concessionária",
  "Locadora de Veículos",
  "Estacionamento",
  "Posto de Combustível",
  "Chaveiro",
  "Lavanderia",
  "Costureira",
  "Alfaiataria",
  "Tatuador",
  "Fotógrafo",
  "Buffet Infantil",
  "Buffet de Casamento",
  "Espaço para Eventos",
  "Casa de Festas",
  "Hotel",
  "Pousada",
  "Hostel",
  "Motel",
  "Agência de Turismo",
  "Agência de Viagens",
  "Agência de Marketing",
  "Agência de Publicidade",
  "Estúdio de Design",
  "Estúdio de Tatuagem",
  "Estúdio de Piercing",
];
