import type { BusinessData } from "./analyze-lead";

export const MOCK_LEADS: BusinessData[] = [
  {
    name: "Padaria Pão Dourado",
    category: "Padaria",
    city: "São Paulo",
    address: "R. das Flores, 123 - Vila Mariana",
    phone: "(11) 3456-7890",
    instagram_handle: "@paodourado",
    instagram_last_post_days: 210,
    has_website: false,
    has_whatsapp: false,
    latitude: -23.5893,
    longitude: -46.6345,
  },
  {
    name: "Barbearia Navalha de Ouro",
    category: "Barbearia",
    city: "São Paulo",
    address: "Av. Paulista, 900",
    phone: "(11) 99887-1122",
    whatsapp: "(11) 99887-1122",
    instagram_handle: "@navalhadeouro",
    instagram_last_post_days: 12,
    has_website: false,
    has_whatsapp: true,
    latitude: -23.5613,
    longitude: -46.6558,
  },
  {
    name: "Restaurante Fogão de Barro",
    category: "Restaurante",
    city: "São Paulo",
    address: "R. Aspicuelta, 400 - Vila Madalena",
    phone: "(11) 3812-4455",
    website: "fogaodebarro.com.br",
    whatsapp: "(11) 98111-2233",
    instagram_handle: "@fogaodebarro",
    instagram_last_post_days: 3,
    has_website: true,
    has_whatsapp: true,
    latitude: -23.5462,
    longitude: -46.6912,
  },
  {
    name: "Pet Shop Amigo Fiel",
    category: "Pet Shop",
    city: "São Paulo",
    address: "R. Teodoro Sampaio, 1500",
    phone: "(11) 3061-9090",
    instagram_handle: "@amigofielpet",
    instagram_last_post_days: 145,
    has_website: false,
    has_whatsapp: false,
    latitude: -23.5581,
    longitude: -46.6836,
  },
  {
    name: "Studio Pilates Corpo Leve",
    category: "Academia",
    city: "São Paulo",
    address: "R. Oscar Freire, 250",
    phone: "(11) 2345-6789",
    whatsapp: "(11) 97777-8888",
    has_website: false,
    has_whatsapp: true,
    latitude: -23.5629,
    longitude: -46.6708,
  },
  {
    name: "Ótica Visão Clara",
    category: "Ótica",
    city: "São Paulo",
    address: "R. Augusta, 2100",
    phone: "(11) 3081-3030",
    website: "oticavisaoclara.com.br",
    whatsapp: "(11) 96666-5544",
    instagram_handle: "@oticavisaoclara",
    instagram_last_post_days: 25,
    has_website: true,
    has_whatsapp: true,
    latitude: -23.5567,
    longitude: -46.6626,
  },
  {
    name: "Salão Beleza Pura",
    category: "Salão",
    city: "São Paulo",
    address: "R. Haddock Lobo, 800",
    phone: "(11) 3062-1010",
    instagram_handle: "@belezapurasp",
    instagram_last_post_days: 320,
    has_website: false,
    has_whatsapp: false,
    latitude: -23.5556,
    longitude: -46.6669,
  },
  {
    name: "Hamburgueria Fogo Alto",
    category: "Restaurante",
    city: "São Paulo",
    address: "R. Fradique Coutinho, 200",
    phone: "(11) 3814-2020",
    whatsapp: "(11) 95555-4433",
    instagram_handle: "@fogoaltoburger",
    instagram_last_post_days: 60,
    has_website: false,
    has_whatsapp: true,
    latitude: -23.5507,
    longitude: -46.6899,
  },
];
